### PR TITLE
Reddit scraper now works with the new UI. Fixes #57

### LINKED ISSUE #57: Reddit is Broken due to new UI
Reddit is broken due to the new UI.  The Reddit scraper functionality needs to be updated.

### PR DESCRIPTION
**Pull request by mauricetmeyer**

### CODE REVIEW

**Comment by frankcash** [comment]
💯 Thank you so much

**Comment by mauricetmeyer** [comment]
@frankcash No Problem! This was actually my first open source contribution, so I'm happy that it worked out so well.

**Comment by frankcash** [comment]
👍

**Comment by frankcash** [comment]
I'll get it live on the site some time tomorrow!

**Pull request merged**
