### PR TITLE
More colorful icons for different news sources!

### PR DESCRIPTION
**Pull request by bkjoel**
# Related Issue	
Comment buttons too dark -
https://github.com/frankcash/HackerQueue/issues/41

# Changes Proposed	
Changed the icons to more colorful ones,
Lobster's are now bourdeaux-ish rectangles, Reddit's are now the reddit's alien.

#### Caveats	
none.

### CODE REVIEW

**Comment by bkjoel** [comment]
Not sure if this is the place for it - but I was have some trouble cloning and running the project, it wasn't clear for me from the start that I needed to set up a postgreSQL server on my machine in order to run HackerQueue with `npm start` or `node app.js`.
I could add some information in the README.md on running the project, do you think it's appropriate?

**Comment by frankcash** [comment]
I would appreciate if you do that as a second PR!

also,  could you please attach screenshots of the UI changes ot make it easier for me to conceptualize?

**Comment by bkjoel** [comment]
Definitely,
Old icons - 
image
New icons - 
image

**Comment by frankcash** [comment]
This is awesome!

**Pull request merged**
