### PR TITLE
Add Travis CI support

### PR DESCRIPTION
**Pull request by gsrajadh**
I have added Travis CI support for the application. You will need to modify the badge with your Repo URL after you turn on Travis CI support for your repo in the following line : 
```
+[![Build Status](https://travis-ci.org/gsrajadh/HackerQueue.svg?branch=master)](https://travis-ci.org/gsrajadh/HackerQueue)
```
Please let me know if you have any questions.

### CODE REVIEW

**Comment by frankcash** [comment]
Could you change the Travis file to run against node 6?

**Comment by gsrajadh** [comment]
@frankcash updated. please let me know if you need anything else

**Comment by gsrajadh** [comment]
@frankcash Hey I tried changing it to node 6 but its creating dependency issue possibly due to jshintrc version. Looks like this from the error message : https://github.com/jshint/jshint/issues/2922
Any idea how to resolve this as I am unfamiliar with grunt ?

**Comment by gsrajadh** [comment]
@frankcash I managed resolving the issue ! Please let me know if you want any other changes

**Comment by frankcash** [comment]
Thank you so much for your contribution 👍

**Comment by gsrajadh** [comment]
Happy to help! Can you please add hacktoberfest label to this PR? Thanks!

**Pull request merged**
